#!/bin/bash
##################################################################################################
#   regr script
#
#   Author : Spyridakis Christos
#   Created Date : 8/10/2019
#   Last Updated : 8/10/2019
#   Email : spyridakischristos@gmail.com
#
#   Description : 
#
#
#
#
##################################################################################################
